# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7LzRxLgOwD4Q4LBC-SlublUjAMdJaEG
"""

import numpy as np
import pandas as pd
from sklearn.model

C = 0.55 #GridSearchCV
epsilon = 0.255 #from GridSearchCV
best_svr = SVR(C = C, epsilon = epsilon)
best_svr.fit(X_total_train_red, y_total_train_red)
y_pred_svr = best_svr.predict(X_final_test_red)
mse_svr = mean_squared_error(y_final_test_red, y_pred_svr)
print(f"MSE on the test set with C: {C: .2f} and epsilon: {epsilon: .2f} is {mse_svr: .2f}")